<?php
/**
 * Shop System Plugins
 * - Terms of use can be found under
 * https://guides.qenta.com/shop_plugins:info
 * - License can be found under:
 * https://github.com/qenta-cee/oxid-qcp/blob/master/LICENSE
*/

$sLangName = "English";

$aLang = array(
    "charset" => 'UTF-8',
    'SHOP_MODULE_GROUP_qcp_parameters' => 'Parameter Configurations',
    'SHOP_MODULE_sQcpCustomerId' => 'Customer ID',
    'HELP_SHOP_MODULE_sQcpCustomerId' => 'Customer number you received from QENTA (customerId, i.e.(D2#####).<br /><a href="https://guides.qenta.com/request_parameters#customerid" target="_blank">More information: customerId</a>',
    'SHOP_MODULE_sQcpShopId' => 'Shop ID',
    'HELP_SHOP_MODULE_sQcpShopId' => 'Shop identifier (<a href="https://guides.qenta.com/request_parameters#shopid" target="_blank">shopId</a>) in case of more than one shop. Please contact our <a href="https://guides.qenta.com/sales" target="_blank">sales teams</a> to activate this feature. <br /><a href="https://guides.qenta.com/request_parameters#shopid" target="_blank">More information: shopId</a>',
    'SHOP_MODULE_sQcpSecret' => 'Secret',
    'HELP_SHOP_MODULE_sQcpSecret' => 'String which you received from QENTA for signing and validating data to prove their authenticity. <br /><a href="https://guides.qenta.com/security:start#secret_and_fingerprint" target="_blank">More information: secret</a>',
    'SHOP_MODULE_sQcpImageUrl' => 'URL to image on payment page',
    'HELP_SHOP_MODULE_sQcpImageUrl' => 'URL to an image/logo which is displayed during the payment process in QENTA Checkout Page. <a href="https://guides.qenta.com/request_parameters#imageurl" target="_blank">More information: imageUrl</a>',
    'SHOP_MODULE_sQcpServiceUrl' => 'URL to imprint page',
    'HELP_SHOP_MODULE_sQcpServiceUrl' => 'URL on the payment page which leads to the imprint page of the online shop. <a href="https://guides.qenta.com/request_parameters#serviceurl" target="_blank">More information: serviceUrl</a>',
    'SHOP_MODULE_sQcpDisplayText' => 'Text on payment page',
    'HELP_SHOP_MODULE_sQcpDisplayText' => 'Text displayed during the payment process, i.e. "Thank you for ordering in xy-shop". <a href="https://guides.qenta.com/request_parameters#displaytext" target="_blank">More information: displayText</a>',
    'SHOP_MODULE_bQcpAutoDeposit' => 'Automated deposit',
    'HELP_SHOP_MODULE_bQcpAutoDeposit' => 'Enabling an automated deposit of payments.  <a href="https://guides.qenta.com/request_parameters#autodeposit" target="_blank">More information</a>. Please contact our <a href="https://guides.qenta.com/sales" target="_blank">sales teams</a> to activate this feature.',
    'SHOP_MODULE_sQcpBackgroundColor' => 'Background color for credit card logos',
    'HELP_SHOP_MODULE_sQcpBackgroundColor' => 'Background color for the image containing the credit card brand logos. <a href="https://guides.qenta.com/request_parameters#backgroundcolor" target="_blank">More information: backgroundColor</a>',
    'SHOP_MODULE_bQcpUseLayout' => 'Device type optimization',
    'HELP_SHOP_MODULE_bQcpUseLayout' => 'Forward device type for which QENTA Checkout Page should be optimized ("desktop", "tablet" or "smartphone"; parameter <a href="https://guides.qenta.com/request_parameters#layout" target="_blank">layout</a>). Please contact our <a href="https://guides.qenta.com/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.qenta.com/request_parameters#layout" target="_blank">More information: layout</a>',
    'SHOP_MODULE_sQcpPluginMode' => 'Plugin mode',
    'SHOP_MODULE_sQcpPluginMode_Demo' => 'Demo',
    'SHOP_MODULE_sQcpPluginMode_Test' => 'Test',
    'SHOP_MODULE_sQcpPluginMode_Live' => 'Production',
    'HELP_SHOP_MODULE_sQcpPluginMode' => 'For integration, select predefined configuration settings or "Production" for live systems.',
    'SHOP_MODULE_bQcpDuplicateRequestCheck' => 'Check for duplicate requests',
    'HELP_SHOP_MODULE_bQcpDuplicateRequestCheck' => 'Checking duplicate requests made by your consumer. <a href="https://guides.qenta.com/request_parameters#duplicaterequestcheck" target="_blank">More information: duplicateRequestCheck</a>',
    'SHOP_MODULE_sQcpConfirmMail' => 'Notification e-mail',
    'HELP_SHOP_MODULE_sQcpConfirmMail' => 'Receiving notification by e-mail regarding the orders of your consumers if an error occurred in the communication between QENTA and your online shop. Please contact our <a href="https://guides.qenta.com/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.qenta.com/request_parameters#confirmmail" target="_blank">More information: confirmMail</a>',
    'SHOP_MODULE_sQcpMaxRetries' => 'Max. retries',
    'HELP_SHOP_MODULE_sQcpMaxRetries' => 'Definition of maximum number of payment attempts regarding a certain order. Please contact our <a href="https://guides.qenta.com/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.qenta.com/request_parameters#maxretries" target="_blank">More information: maxRetries</a>',
    'SHOP_MODULE_sQcpPaymentTypeSortOrder' => 'Payment method sort order',
    'HELP_SHOP_MODULE_sQcpPaymentTypeSortOrder' => 'Sort order of payment methods and sub-methods in the payment method selection area. Please contact our <a href="https://guides.qenta.com/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.qenta.com/request_parameters#paymenttypesortorder" target="_blank">More information: paymenttypeSortOrder</a>',
    'SHOP_MODULE_GROUP_qcp_settings' => 'Plugin Configuration',
    'SHOP_MODULE_bQcpSendAdditionalCustomerData' => 'Forward consumer data',
    'HELP_SHOP_MODULE_bQcpSendAdditionalCustomerData' => 'Forwarding shipping and billing data about your consumer to the respective financial service provider.',
    'SHOP_MODULE_bQcpSendAdditionalBasketData' => 'Forward basket data',
    'HELP_SHOP_MODULE_bQcpSendAdditionalBasketData' => 'Forwarding basket data to the respective financial service provider.',
    'SHOP_MODULE_bQcpLogConfirmations' => 'Save payment process results',
    'HELP_SHOP_MODULE_bQcpLogConfirmations' => 'Save all results regarding the payment process, i.e. each QENTA Checkout Server response to the confirmation URL.',
    'SHOP_MODULE_sQcpCheckoutFolder' => 'Folder for initiated orders',
    'HELP_SHOP_MODULE_sQcpCheckoutFolder' => 'Selecting folder into which new orders are stored.',
    'SHOP_MODULE_sQcpCheckoutFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sQcpCheckoutFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sQcpCheckoutFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sQcpSuccessFolder' => 'Folder for orders with successful payment',
    'HELP_SHOP_MODULE_sQcpSuccessFolder' => 'Selecting folder into which successful orders are stored.',
    'SHOP_MODULE_sQcpSuccessFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sQcpSuccessFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sQcpSuccessFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sQcpPendingFolder' => 'Folder for orders with pending payment',
    'HELP_SHOP_MODULE_sQcpPendingFolder' => 'Selecting folder into which pending orders are stored.',
    'SHOP_MODULE_sQcpPendingFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sQcpPendingFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sQcpPendingFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sQcpCancelFolder' => 'Folder for orders with canceled payment',
    'HELP_SHOP_MODULE_sQcpCancelFolder' => 'Selecting folder into which canceled orders are stored.',
    'SHOP_MODULE_sQcpCancelFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sQcpCancelFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sQcpCancelFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sQcpFailureFolder' => 'Folder for orders with failed payment',
    'HELP_SHOP_MODULE_sQcpFailureFolder' => 'Selecting folder into which failed orders are stored.',
    'SHOP_MODULE_sQcpFailureFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sQcpFailureFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sQcpFailureFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_bQcpDisableDeviceDetection' => 'Disable iframe for mobile devices',
    'HELP_SHOP_MODULE_bQcpDisableDeviceDetection' => 'Redirect your consumer instead of displaying QENTA Checkout Page in an iframe when visiting your online shop using a mobile device or a tablet.',
    'SHOP_MODULE_sQcpShopName' => 'Shop prefix in posting text',
    'HELP_SHOP_MODULE_sQcpShopName' => 'Reference to your online shop on your consumer\'s invoice, limited to 9 characters (used together with the order number to create the parameter <a href="https://guides.qenta.com/request_parameters#customerstatement" target="_blank">customerStatement</a>',
    'SHOP_MODULE_GROUP_qcp_iframe_settings' => 'Iframe settings',
    'SHOP_MODULE_bQcp_bancontact_mistercash_UseIframe' => 'Bancontact - use iframe',
    'SHOP_MODULE_bQcp_ccard_UseIframe' => 'Credit Card - use iframe',
    'SHOP_MODULE_bQcp_ccard-moto_UseIframe' => 'Credit Card Mail Order / Telephone Order - use iframe',
    'SHOP_MODULE_bQcp_masterpass_UseIframe' => 'masterpass - use iframe',
    'SHOP_MODULE_bQcp_ekonto_UseIframe' => 'eKonto - use iframe',
    'SHOP_MODULE_bQcp_epay_bg_UseIframe' => 'ePay.bg - use iframe',
    'SHOP_MODULE_bQcp_eps_UseIframe' => 'eps Online-&Uuml;berweisung - use iframe',
    'SHOP_MODULE_bQcp_giropay_UseIframe' => 'giropay - use iframe',
    'SHOP_MODULE_bQcp_idl_UseIframe' => 'iDEAL - use iframe',
    'SHOP_MODULE_bQcp_installment_UseIframe' => 'Installment - use iFrame',
    'SHOP_MODULE_bQcp_invoice_b2b_UseIframe' => 'Invoice B2B - use iframe',
    'SHOP_MODULE_bQcp_invoice_b2c_UseIframe' => 'Invoice B2C - use iframe',
    'SHOP_MODULE_bQcp_maestro_UseIframe' => 'Maestro SecureCode - use iframe',
    'SHOP_MODULE_bQcp_moneta_UseIframe' => 'moneta.ru - use iframe',
    'SHOP_MODULE_bQcp_paypal_UseIframe' => 'PayPal - use iframe',
    'SHOP_MODULE_bQcp_pbx_UseIframe' => 'paybox - use iframe',
    'SHOP_MODULE_bQcp_poli_UseIframe' => 'POLi - use iframe',
    'SHOP_MODULE_bQcp_przelewy24_UseIframe' => 'Przelewy24 - use iframe',
    'SHOP_MODULE_bQcp_psc_UseIframe' => 'paysafecard - use iframe',
    'SHOP_MODULE_bQcp_select_UseIframe' => 'Payment Selection - use iframe',
    'SHOP_MODULE_bQcp_sepa-dd_UseIframe' => 'SEPA Direct Debit - use iframe',
    'SHOP_MODULE_bQcp_skrillwallet_UseIframe' => 'Skrill Digital Wallet - use iframe',
    'SHOP_MODULE_bQcp_sofortueberweisung_UseIframe' => 'Online bank transfer. - use iframe',
    'SHOP_MODULE_bQcp_tatrapay_UseIframe' => 'TatraPay - use iframe',
    'SHOP_MODULE_bQcp_trustly_UseIframe' => 'Trustly - use iframe',
    'SHOP_MODULE_bQcp_voucher_UseIframe' => 'My Voucher - use iframe',
    'SHOP_MODULE_bQcp_trustpay_UseIframe' => 'TrustPay - use iframe',
    'SHOP_MODULE_GROUP_qcp_installment_invoice_settings' => 'Installment/Invoice Settings',
    'SHOP_MODULE_sQcpInstallmentProvider' => 'Installment Provider',
    'SHOP_MODULE_sQcpInvoiceProvider' => 'Invoice Provider',
    'HELP_SHOP_MODULE_sQcpInvoiceProvider' => 'Set respective invoice provider. Input will be ignored if invoice is not enabled.',
    'HELP_SHOP_MODULE_sQcpInstallmentProvider' => 'Set respective installment provider. Input will be ignored if installment is not enabled.',
    'SHOP_MODULE_sQcpInvoiceProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sQcpInvoiceProvider_QENTA' => 'QENTA',
    'SHOP_MODULE_sQcpInvoiceProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_sQcpInstallmentProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sQcpInstallmentProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_bQcpPayolutionAllowDifferingAddresses' => 'For payolution: Allowing shipping address to differ from billing address.',
    'SHOP_MODULE_bQcpInvoiceb2bTrustedShopsCheckbox' => 'Display "Trusted Shops"-checkbox for payolution invoice B2B',
    'HELP_SHOP_MODULE_bQcpInvoiceb2bTrustedShopsCheckbox' => 'If your online shop is certified by "Trusted Shops", display the corresponding checkbox with payolution terms for the consumer to agree with during the checkout process.',
    'SHOP_MODULE_bQcpInvoiceb2cTrustedShopsCheckbox' => 'Display "Trusted Shops"-checkbox for payolution invoice B2C',
    'HELP_SHOP_MODULE_bQcpInvoiceb2cTrustedShopsCheckbox' => 'If your online shop is certified by "Trusted Shops", display the corresponding checkbox with payolution terms for the consumer to agree with during the checkout process.',
    'SHOP_MODULE_bQcpInstallmentTrustedShopsCheckbox' => 'Display "Trusted Shops"-checkbox for payolution installment',
    'HELP_SHOP_MODULE_bQcpInstallmentTrustedShopsCheckbox' => 'If your online shop is certified by "Trusted Shops", display the corresponding checkbox with payolution terms for the consumer to agree with during the checkout process.',
    'SHOP_MODULE_sQcpPayolutionMId' => 'payolution mID',
    'HELP_SHOP_MODULE_sQcpPayolutionMId' => 'Your payolution merchant ID consisting of the base64-encoded company name which is used in the link for "consent" to the payolution terms.(https://www.base64encode.org/)',
    'QENTA_CHECKOUT_PAGE_BANCONTACT_MISTERCASH_LABEL' => 'Bancontact',
    'QENTA_CHECKOUT_PAGE_CCARD_LABEL' => 'Credit Card',
    'QENTA_CHECKOUT_PAGE_CCARD-MOTO_LABEL' => 'Credit Card Mail Order / Telephone Order',
    'QENTA_CHECKOUT_PAGE_EKONTO_LABEL' => 'eKonto',
    'QENTA_CHECKOUT_PAGE_EPAY_BG_LABEL' => 'ePay.bg',
    'QENTA_CHECKOUT_PAGE_EPS_LABEL' => 'eps Online-&Uuml;berweisung',
    'QENTA_CHECKOUT_PAGE_GIROPAY_LABEL' => 'giropay',
    'QENTA_CHECKOUT_PAGE_IDL_LABEL' => 'iDEAL',
    'QENTA_CHECKOUT_PAGE_INSTALLMENT_LABEL' => 'Installment',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2B_LABEL' => 'Invoice B2B',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2C_LABEL' => 'Invoice B2C',
    'QENTA_CHECKOUT_PAGE_MAESTRO_LABEL' => 'Maestro SecureCode',
    'QENTA_CHECKOUT_PAGE_MONETA_LABEL' => 'moneta.ru',
    'QENTA_CHECKOUT_PAGE_MASTERPASS_LABEL' => 'masterpass',
    'QENTA_CHECKOUT_PAGE_PAYPAL_LABEL' => 'PayPal',
    'QENTA_CHECKOUT_PAGE_PBX_LABEL' => 'paybox',
    'QENTA_CHECKOUT_PAGE_POLI_LABEL' => 'POLi',
    'QENTA_CHECKOUT_PAGE_PRZELEWY24_LABEL' => 'Przelewy24',
    'QENTA_CHECKOUT_PAGE_PSC_LABEL' => 'paysafecard',
    'QENTA_CHECKOUT_PAGE_SELECT_LABEL' => 'Payment Selection',
    'QENTA_CHECKOUT_PAGE_SEPA-DD_LABEL' => 'SEPA Direct Debit',
    'QENTA_CHECKOUT_PAGE_SKRILLWALLET_LABEL' => 'Skrill Digital Wallet',
    'QENTA_CHECKOUT_PAGE_SOFORTUEBERWEISUNG_LABEL' => 'Online bank transfer.',
    'QENTA_CHECKOUT_PAGE_TATRAPAY_LABEL' => 'TatraPay',
    'QENTA_CHECKOUT_PAGE_TRUSTLY_LABEL' => 'Trustly',
    'QENTA_CHECKOUT_PAGE_VOUCHER_LABEL' => 'My Voucher',
    'QENTA_CHECKOUT_PAGE_TRUSTPAY_LABEL' => 'TrustPay',
    'QENTA_CHECKOUT_PAGE_BANCONTACT_MISTERCASH_DESC' => '',
    'QENTA_CHECKOUT_PAGE_CCARD_DESC' => '',
    'QENTA_CHECKOUT_PAGE_CCARD-MOTO_DESC' => '',
    'QENTA_CHECKOUT_PAGE_EKONTO_DESC' => '',
    'QENTA_CHECKOUT_PAGE_EPAY_BG_DESC' => '',
    'QENTA_CHECKOUT_PAGE_ELV_DESC' => '',
    'QENTA_CHECKOUT_PAGE_EPS_DESC' => '',
    'QENTA_CHECKOUT_PAGE_GIROPAY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_IDL_DESC' => '',
    'QENTA_CHECKOUT_PAGE_INSTALLMENT_DESC' => '',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2B_DESC' => '',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2C_DESC' => '',
    'QENTA_CHECKOUT_PAGE_MAESTRO_DESC' => '',
    'QENTA_CHECKOUT_PAGE_MONETA_DESC' => '',
    'QENTA_CHECKOUT_PAGE_MASTERPASS_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PAYPAL_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PBX_DESC' => '',
    'QENTA_CHECKOUT_PAGE_POLI_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PRZELEWY24_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PSC_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SELECT_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SEPA-DD_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SKRILLWALLET_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SOFORTUEBERWEISUNG_DESC' => '',
    'QENTA_CHECKOUT_PAGE_TATRAPAY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_TRUSTLY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_VOUCHER_DESC' => '',
    'QENTA_CHECKOUT_PAGE_TRUSTPAY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_COMMUNICATION_ERROR' => 'Communication error with payment service provider. Please try again later.',
    'QCP_SUBMIT' => 'Submit',
    'QCP_SUBMIT_CONFIG' => 'Submit QENTA Checkout Page Configuration',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_RECEIVER' => 'Send to',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_CONFIG_STRING' => 'Configuration',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_DESC_TEXT' => 'Comment',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_RETURN_MAIL' => 'Reply to e-mail address',
    'ORDER_OVERVIEW_QCP_FINANCIALINSTITUTION' => 'financialInstitution',
    'ORDER_OVERVIEW_QCP_LANGUAGE' => 'language',
    'ORDER_OVERVIEW_QCP_ORDERNUMBER' => 'orderNumber',
    'ORDER_OVERVIEW_QCP_AMOUNT' => 'amount',
    'ORDER_OVERVIEW_QCP_CURRENCY' => 'currency',
    'ORDER_OVERVIEW_QCP_GATEWAYCONTRACTNUMBER' => 'gatewayContractNumber',
    'ORDER_OVERVIEW_QCP_GATEWAYREFERENCENUMBER' => 'gatewayReferenceNumber',
    'ORDER_OVERVIEW_QCP_MESSAGE' => 'message',
    'ORDER_OVERVIEW_QCP_LIABILITYSHIFTINDICATOR' => 'liabilityShiftIndicator',
    'ORDER_OVERVIEW_QCP_INSTRUMENTCOUNTRY' => 'instrumentCountry',
    'ORDER_OVERVIEW_QCP_RISKINTERCEPT' => 'riskIntercept',
    'ORDER_OVERVIEW_QCP_RISKREASONCODE' => 'riskReasonCode',
    'ORDER_OVERVIEW_QCP_RISKREASONMESSAGE' => 'riskReasonMessage',
    'ORDER_OVERVIEW_QCP_RISKRETURNCODE' => 'riskReturnCode',
    'ORDER_OVERVIEW_QCP_RISKRETURNMESSAGE' => 'riskReturnMessage',
    'ORDER_OVERVIEW_QCP_PAYMENTSTATE' => 'paymentState',
    'ORDER_OVERVIEW_QCP_LANG' => 'lang',
    'ORDER_OVERVIEW_QCP_LANGID' => 'langId',
    'ORDER_OVERVIEW_QCP_CHECKOUTTYPE' => 'checkoutType',
    'ORDER_OVERVIEW_QCP_AVSRESPONSECODE' => 'avsResponseCode',
    'ORDER_OVERVIEW_QCP_AVSRESPONSEMESSAGE' => 'avsResponseMessage',
    'ORDER_OVERVIEW_QCP_AVSPROVIDERRESULTCODE' => 'avsProviderResultCode',
    'ORDER_OVERVIEW_QCP_AVSPROVIDERRESULTMESSAGE' => 'avsProviderResultMessage',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERNAME' => 'idealConsumerName',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERBIC' => 'idealConsumerBIC',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERCITY' => 'idealConsumerCity',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERIBAN' => 'idealConsumerIBAN',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERACCOUNTNUMBER' => 'idealConsumerAccountNumber',
    'ORDER_OVERVIEW_QCP_SENDERACCOUNTOWNER' => 'senderAccountOwner',
    'ORDER_OVERVIEW_QCP_SENDERACCOUNTNUMBER' => 'senderAccountNumber',
    'ORDER_OVERVIEW_QCP_SENDERBANKNUMBER' => 'senderBankNumber',
    'ORDER_OVERVIEW_QCP_SENDERBANKNAME' => 'senderBankName',
    'ORDER_OVERVIEW_QCP_SENDERBIC' => 'senderBIC',
    'ORDER_OVERVIEW_QCP_SENDERIBAN' => 'senderIBAN',
    'ORDER_OVERVIEW_QCP_SENDERCOUNTRY' => 'senderCountry',
    'ORDER_OVERVIEW_QCP_SECURITYCRITERIA' => 'securityCriteria',
    'ORDER_OVERVIEW_QCP_AUTHENTICATED' => ' authenticated ',
    'ORDER_OVERVIEW_QCP_ANONYMOUSPAN' => 'anonymousPan',
    'ORDER_OVERVIEW_QCP_EXPIRY' => 'expiry',
    'ORDER_OVERVIEW_QCP_CARDHOLDER' => 'cardholder',
    'ORDER_OVERVIEW_QCP_MASKEDPAN' => 'maskedPan',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERID' => 'paypalPayerID',
    'ORDER_OVERVIEW_QCP_PAYPALPAYEREMAIL' => 'paypalPayerEmail',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERLASTNAME' => 'paypalPayerLastName',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERFIRSTNAME' => 'paypalPayerFirstName',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSNAME' => 'paypalPayerAddressName',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSCOUNTRY' => 'paypalPayerAddressCountry',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSCOUNTRYCODE' => 'paypalPayerAddressCountryCode',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSCITY' => 'paypalPayerAddressCity',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSSTATE' => 'paypalPayerAddressState',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSSTREET1' => 'paypalPayerAddressStreet1',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSSTREET2' => 'paypalPayerAddressStreet2',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSZIP' => 'paypalPayerAddressZIP',
    'ORDER_OVERVIEW_QCP_MANDATEID' => 'mandateId',
    'ORDER_OVERVIEW_QCP_MANDATESIGNATUREDATE' => 'mandateSignatureDate',
    'ORDER_OVERVIEW_QCP_CREDITORID' => 'creditorId',
    'ORDER_OVERVIEW_QCP_DUEDATE' => 'dueDate',
);
