<?php
/**
 * Shop System Plugins
 * - Terms of use can be found under
 * https://guides.qenta.com/shop_plugins:info
 * - License can be found under:
 * https://github.com/qenta-cee/oxid-qcp/blob/master/LICENSE
*/

$sLangName = "Deutsch";

$aLang = array(
    "charset" => 'UTF-8',
    'SHOP_MODULE_GROUP_qcp_parameters' => 'Parameter Einstellungen',
    'SHOP_MODULE_sQcpCustomerId' => 'Kundennummer',
    'HELP_SHOP_MODULE_sQcpCustomerId' => 'Ihre QENTA-Kundennummer (customerId, im Format D2#####).<br /><a href="https://guides.qenta.com/request_parameters#customerid" target="_blank">Weitere Informationen: customerId</a>',
    'SHOP_MODULE_sQcpShopId' => 'Shop ID',
    'HELP_SHOP_MODULE_sQcpShopId' => 'Shop-Kennung (<a href="https://guides.qenta.com/request_parameters#shopId" target="_blank">shopId</a>) bei mehreren Onlineshops. Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/sales" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.<br /><a href="https://guides.qenta.com/request_parameters#shopid" target="_blank">Weitere Informationen: shopId</a>',
    'SHOP_MODULE_sQcpSecret' => 'Secret',
    'HELP_SHOP_MODULE_sQcpSecret' => 'Geheime Zeichenfolge, die Sie von QENTA erhalten haben, zum Signieren und Validieren von Daten zur Pr&uuml;fung der Authentizit&auml;t.<br /><a href="https://guides.qenta.com/security:start#secret_and_fingerprint" target="_blank">Weitere Informationen: secret</a>',
    'SHOP_MODULE_sQcpImageUrl' => 'URL des Bildes auf der Bezahlseite',
    'HELP_SHOP_MODULE_sQcpImageUrl' => 'URL zu einem Bild/Logo, das w&auml;hrend des Bezahlprozesses in QENTA Checkout Page angezeigt wird.<a href="https://guides.qenta.com/request_parameters#imageurl" target="_blank">Weitere Informationen: imageUrl</a>',
    'SHOP_MODULE_sQcpServiceUrl' => 'URL zur Impressum-Seite',
    'HELP_SHOP_MODULE_sQcpServiceUrl' => 'URL auf der Bezahlseite, die zur Impressum-Seite des Onlineshops f&uuml;hrt.<a href="https://guides.qenta.com/request_parameters#serviceurl" target="_blank">Weitere Informationen: serviceUrl</a>',
    'SHOP_MODULE_sQcpDisplayText' => 'Text auf der Bezahlseite',
    'HELP_SHOP_MODULE_sQcpDisplayText' => 'Text, der w&auml;hrend des Bezahlprozesses angezeigt wird, z.B. "Danke f&uuml;r Ihre Bestellung in xy-Shop."<a href="https://guides.qenta.com/request_parameters#displaytext" target="_blank">Weitere Informationen: displayText</a>',
    'SHOP_MODULE_bQcpAutoDeposit' => 'Automatisches Abbuchen',
    'HELP_SHOP_MODULE_bQcpAutoDeposit' => 'Automatisches Abbuchen der Zahlungen.  <a href="https://guides.qenta.com/request_parameters#autodeposit" target="_blank">Weitere Informationen</a>.  Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/sales" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.',
    'SHOP_MODULE_sQcpBackgroundColor' => 'Hintergrundfarbe f&uuml;r Kreditkarten-Logos',
    'HELP_SHOP_MODULE_sQcpBackgroundColor' => 'Hintergrundfarbe f&uuml;r das Bild, das die Logos der Kreditkarten enth&auml;lt.<a href="https://guides.qenta.com/request_parameters#backgroundcolor" target="_blank">Weitere Informationen: backgroundColor</a>',
    'SHOP_MODULE_bQcpUseLayout' => 'Endger&auml;t-Optimierung',
    'HELP_SHOP_MODULE_bQcpUseLayout' => 'Weiterleitung des Endger&auml;tes, f&uuml;r das QENTA Checkout Page optimiert werden soll ("desktop", "tablet" oder "smartphone"; Parameter <a href="https://guides.qenta.com/doku.php/request_parameters#layout" target="_blank">layout</a>). Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/sales" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.<br /><a href="https://guides.qenta.com/request_parameters#layout" target="_blank">Weitere Informationen: layout</a>',
    'SHOP_MODULE_sQcpPluginMode' => 'Plugin Modus',
    'SHOP_MODULE_sQcpPluginMode_Demo' => 'Demo',
    'SHOP_MODULE_sQcpPluginMode_Test' => 'Test',
    'SHOP_MODULE_sQcpPluginMode_Live' => 'Production',
    'HELP_SHOP_MODULE_sQcpPluginMode' => 'Zum Testen der Integration eine vordefinierte Konfiguration ausw&auml;hlen. F&uuml;r Produktivsysteme "Production" ausw&auml;hlen.',
    'SHOP_MODULE_bQcpDuplicateRequestCheck' => '&Uuml;berpr&uuml;fung auf doppelte Anfragen',
    'HELP_SHOP_MODULE_bQcpDuplicateRequestCheck' => '&Uuml;berpr&uuml;fung auf mehrfache Anfragen seitens Ihres Kunden.<a href="https://guides.qenta.com/request_parameters#duplicaterequestcheck" target="_blank">Weitere Informationen: duplicateRequestCheck</a>',
    'SHOP_MODULE_sQcpConfirmMail' => 'Benachrichtigungsmail',
    'HELP_SHOP_MODULE_sQcpConfirmMail' => 'Benachrichtigung per E-Mail &uuml;ber Zahlungen Ihrer Kunden, falls ein Kommunikationsproblem zwischen QENTA und Ihrem Onlineshop aufgetreten ist. Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/sales" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.<br /><a href="https://guides.qenta.com/request_parameters#confirmmail" target="_blank">Weitere Informationen: confirmMail</a>',
    'SHOP_MODULE_sQcpMaxRetries' => 'Max. Versuche',
    'HELP_SHOP_MODULE_sQcpMaxRetries' => 'Definition der max. m&ouml;glichen Bezahlversuche eines bestimmten Auftrags. Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/sales" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.<br /><a href="https://guides.qenta.com/request_parameters#maxretries" target="_blank">Weitere Informationen: maxRetries</a>',
    'SHOP_MODULE_sQcpPaymentTypeSortOrder' => 'Reihenfolge der Zahlungsmittel',
    'HELP_SHOP_MODULE_sQcpPaymentTypeSortOrder' => 'Reihenfolge der angezeigten Zahlungsmittel im Auswahlbereich. Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/sales" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.<br /><a href="https://guides.qenta.com/request_parameters#paymenttypesortorder" target="_blank">Weitere Informationen: paymenttypeSortOrder</a>',
    'SHOP_MODULE_GROUP_qcp_settings' => 'Plugin-Einstellungen',
    'SHOP_MODULE_bQcpSendAdditionalCustomerData' => 'Verrechnungsdaten des Konsumenten mitsenden',
    'HELP_SHOP_MODULE_bQcpSendAdditionalCustomerData' => 'Weiterleitung der Rechnungs- und Versanddaten des Kunden an den Finanzdienstleister.',
    'SHOP_MODULE_bQcpSendAdditionalBasketData' => 'Warenkorbdaten mitsenden',
    'HELP_SHOP_MODULE_bQcpSendAdditionalBasketData' => 'Weiterleitung des Warenkorbs des Kunden an den Finanzdienstleister.',
    'SHOP_MODULE_bQcpLogConfirmations' => 'Speichern der Bezahlprozess-Ergebnisse',
    'HELP_SHOP_MODULE_bQcpLogConfirmations' => 'Speichern aller Ergebnisse des Bezahlprozesses, d.h. jedes Aufrufs des QENTA Checkout Servers der Best&auml;tigungs-URL.',
    'SHOP_MODULE_sQcpCheckoutFolder' => 'Ordner f&uuml;r neue Bestellungen',
    'HELP_SHOP_MODULE_sQcpCheckoutFolder' => 'Auswahl des Ordners, in den neue Bestellungen gespeichert werden.',
    'SHOP_MODULE_sQcpCheckoutFolder_ORDERFOLDER_NEW' => 'Neu',
    'SHOP_MODULE_sQcpCheckoutFolder_ORDERFOLDER_FINISHED' => 'Bearbeitet',
    'SHOP_MODULE_sQcpCheckoutFolder_ORDERFOLDER_PROBLEMS' => 'Probleme',
    'SHOP_MODULE_sQcpSuccessFolder' => 'Ordner f&uuml;r erfolgreiche Zahlungen',
    'HELP_SHOP_MODULE_sQcpSuccessFolder' => 'Auswahl des Ordners, in den erfolgreich bezahlte Bestellungen gespeichert werden.',
    'SHOP_MODULE_sQcpSuccessFolder_ORDERFOLDER_NEW' => 'Neu',
    'SHOP_MODULE_sQcpSuccessFolder_ORDERFOLDER_FINISHED' => 'Bearbeitet',
    'SHOP_MODULE_sQcpSuccessFolder_ORDERFOLDER_PROBLEMS' => 'Probleme',
    'SHOP_MODULE_sQcpPendingFolder' => 'Ordner f&uuml;r ausstehende Zahlungen',
    'HELP_SHOP_MODULE_sQcpPendingFolder' => 'Auswahl des Ordners, in den Bestellungen mit ausstehendem Zahlungsstatus gespeichert werden.',
    'SHOP_MODULE_sQcpPendingFolder_ORDERFOLDER_NEW' => 'Neu',
    'SHOP_MODULE_sQcpPendingFolder_ORDERFOLDER_FINISHED' => 'Bearbeitet',
    'SHOP_MODULE_sQcpPendingFolder_ORDERFOLDER_PROBLEMS' => 'Probleme',
    'SHOP_MODULE_sQcpCancelFolder' => 'Ordner f&uuml;r abgebrochene Zahlungen',
    'HELP_SHOP_MODULE_sQcpCancelFolder' => 'Auswahl des Ordners, in den Bestellungen mit abgebrochenem Bezahlprozess gespeichert werden.',
    'SHOP_MODULE_sQcpCancelFolder_ORDERFOLDER_NEW' => 'Neu',
    'SHOP_MODULE_sQcpCancelFolder_ORDERFOLDER_FINISHED' => 'Bearbeitet',
    'SHOP_MODULE_sQcpCancelFolder_ORDERFOLDER_PROBLEMS' => 'Probleme',
    'SHOP_MODULE_sQcpFailureFolder' => 'Ordner f&uuml;r fehlerhafte Zahlungen',
    'HELP_SHOP_MODULE_sQcpFailureFolder' => 'Auswahl des Ordners, in den Bestellungen mit fehlerhaftem Bezahlprozess gespeichert werden.',
    'SHOP_MODULE_sQcpFailureFolder_ORDERFOLDER_NEW' => 'Neu',
    'SHOP_MODULE_sQcpFailureFolder_ORDERFOLDER_FINISHED' => 'Bearbeitet',
    'SHOP_MODULE_sQcpFailureFolder_ORDERFOLDER_PROBLEMS' => 'Probleme',
    'SHOP_MODULE_bQcpDisableDeviceDetection' => 'iFrame f&uuml;r mobile Ger&auml;te deaktivieren',
    'HELP_SHOP_MODULE_bQcpDisableDeviceDetection' => 'Bei Verwendung eines mobilen Ger&auml;tes wird der Konsument zur QENTA Checkout Page weitergeleitet, d.h. diese wird in diesem Fall nicht im iFrame angezeigt.',
    'SHOP_MODULE_sQcpShopName' => 'Shop-Pr&auml;fix auf Buchungstext',
    'HELP_SHOP_MODULE_sQcpShopName' => 'Referenz zu Ihrem Onlineshop im Buchungstext f&uuml;r Ihren Kunden, max. 9 Zeichen (wird zusammen mit der Auftragsnummer zum Erstellen des Parameters <a href="https://guides.qenta.com/request_parameters#customerstatement" target="_blank">customerStatement</a> verwendet.)',
    'SHOP_MODULE_GROUP_qcp_iframe_settings' => 'iFrame-Einstellungen',
    'SHOP_MODULE_bQcp_bancontact_mistercash_UseIframe' => 'Bancontact - iFrame verwenden',
    'SHOP_MODULE_bQcp_ccard_UseIframe' => 'Kreditkarte iFrame verwenden',
    'SHOP_MODULE_bQcp_ccard-moto_UseIframe' => 'Kreditkarte Mail Order / Telephone Order - iFrame verwenden',
    'SHOP_MODULE_bQcp_masterpass_UseIframe' => 'masterpass - iFrame verwenden',
    'SHOP_MODULE_bQcp_ekonto_UseIframe' => 'eKonto - iFrame verwenden',
    'SHOP_MODULE_bQcp_epay_bg_UseIframe' => 'ePay.bg - iFrame verwenden',
    'SHOP_MODULE_bQcp_eps_UseIframe' => 'eps Online-&Uuml;berweisung - iFrame verwenden',
    'SHOP_MODULE_bQcp_giropay_UseIframe' => 'giropay - iFrame verwenden',
    'SHOP_MODULE_bQcp_idl_UseIframe' => 'iDEAL - iFrame verwenden',
    'SHOP_MODULE_bQcp_installment_UseIframe' => 'Kauf auf Raten - iFrame verwenden',
    'SHOP_MODULE_bQcp_invoice_b2b_UseIframe' => 'Kauf auf Rechnung B2B - iFrame verwenden',
    'SHOP_MODULE_bQcp_invoice_b2c_UseIframe' => 'Kauf auf Rechnung B2C - iFrame verwenden',
    'SHOP_MODULE_bQcp_maestro_UseIframe' => 'Maestro SecureCode - iFrame verwenden',
    'SHOP_MODULE_bQcp_moneta_UseIframe' => 'moneta.ru - iFrame verwenden',
    'SHOP_MODULE_bQcp_paypal_UseIframe' => 'PayPal - iFrame verwenden',
    'SHOP_MODULE_bQcp_pbx_UseIframe' => 'paybox - iFrame verwenden',
    'SHOP_MODULE_bQcp_poli_UseIframe' => 'POLi - iFrame verwenden',
    'SHOP_MODULE_bQcp_przelewy24_UseIframe' => 'Przelewy24 - iFrame verwenden',
    'SHOP_MODULE_bQcp_psc_UseIframe' => 'paysafecard - iFrame verwenden',
    'SHOP_MODULE_bQcp_select_UseIframe' => 'Zahlungsmittelauswahl - iFrame verwenden',
    'SHOP_MODULE_bQcp_sepa-dd_UseIframe' => 'SEPA Lastschrift - iFrame verwenden',
    'SHOP_MODULE_bQcp_skrillwallet_UseIframe' => 'Skrill Digital Wallet - iFrame verwenden',
    'SHOP_MODULE_bQcp_sofortueberweisung_UseIframe' => 'Sofort. - iFrame verwenden',
    'SHOP_MODULE_bQcp_tatrapay_UseIframe' => 'TatraPay - iFrame verwenden',
    'SHOP_MODULE_bQcp_trustly_UseIframe' => 'Trustly - iFrame verwenden',
    'SHOP_MODULE_bQcp_voucher_UseIframe' => 'Mein Gutschein - iFrame verwenden',
    'SHOP_MODULE_bQcp_trustpay_UseIframe' => 'TrustPay - iFrame verwenden',
    'SHOP_MODULE_GROUP_qcp_installment_invoice_settings' => 'Einstellungen f&uuml;r Kauf auf Raten/Rechnung',
    'SHOP_MODULE_sQcpInstallmentProvider' => 'Provider f&uuml;r Kauf auf Raten',
    'SHOP_MODULE_sQcpInvoiceProvider' => 'Provider f&uuml;r Kauf auf Rechnung',
    'HELP_SHOP_MODULE_sQcpInvoiceProvider' => 'Auswahl des Providers f&uuml;r Kauf auf Rechnung. Eingabe wird ignoriert, wenn Kauf auf Rechnung nicht freigeschalten ist.',
    'HELP_SHOP_MODULE_sQcpInstallmentProvider' => 'Auswahl des Providers f&uuml;r Kauf auf Raten. Eingabe wird ignoriert, wenn Kauf auf Raten nicht freigeschalten ist.',
    'SHOP_MODULE_sQcpInvoiceProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sQcpInvoiceProvider_QENTA' => 'QENTA',
    'SHOP_MODULE_sQcpInvoiceProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_sQcpInstallmentProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sQcpInstallmentProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_bQcpPayolutionAllowDifferingAddresses' => 'F&uuml;r payolution: Rechnungsadresse darf von der Lieferadresse abweichen.',
    'SHOP_MODULE_bQcpInvoiceb2bTrustedShopsCheckbox' => 'Anzeige der "Trusted Shops"-Checkbox f&uuml;r Kauf auf Rechnung B2B von payolution',
    'HELP_SHOP_MODULE_bQcpInvoiceb2bTrustedShopsCheckbox' => 'Anzeige der Checkbox mit den payolution-Bedingungen, die vom Kunden w&auml;hrend des Bezahlprozesses best&auml;tigt werden m&uuml;ssen, wenn Ihr Onlineshop als "Trusted Shop" zertifiziert ist.',
    'SHOP_MODULE_bQcpInvoiceb2cTrustedShopsCheckbox' => 'Anzeige der "Trusted Shops"-Checkbox f&uuml;r Kauf auf Rechnung B2C von payolution',
    'HELP_SHOP_MODULE_bQcpInvoiceb2cTrustedShopsCheckbox' => 'Anzeige der Checkbox mit den payolution-Bedingungen, die vom Kunden w&auml;hrend des Bezahlprozesses best&auml;tigt werden m&uuml;ssen, wenn Ihr Onlineshop als "Trusted Shop" zertifiziert ist.',
    'SHOP_MODULE_bQcpInstallmentTrustedShopsCheckbox' => 'Anzeige der "Trusted Shops"-Checkbox f&uuml;r Kauf auf Raten von payolution',
    'HELP_SHOP_MODULE_bQcpInstallmentTrustedShopsCheckbox' => 'Anzeige der Checkbox mit den payolution-Bedingungen, die vom Kunden w&auml;hrend des Bezahlprozesses best&auml;tigt werden m&uuml;ssen, wenn Ihr Onlineshop als "Trusted Shop" zertifiziert ist.',
    'SHOP_MODULE_sQcpPayolutionMId' => 'payolution mID',
    'HELP_SHOP_MODULE_sQcpPayolutionMId' => 'payolution-H&auml;ndler-ID, bestehend aus dem Base64-enkodierten Firmennamen, die f&uuml;r den Link "Einwilligen" gesetzt werden kann (https://www.base64encode.org/).',
    'QENTA_CHECKOUT_PAGE_BANCONTACT_MISTERCASH_LABEL' => 'Bancontact',
    'QENTA_CHECKOUT_PAGE_CCARD_LABEL' => 'Kreditkarte',
    'QENTA_CHECKOUT_PAGE_CCARD-MOTO_LABEL' => 'Kreditkarte Mail Order / Telephone Order',
    'QENTA_CHECKOUT_PAGE_EKONTO_LABEL' => 'eKonto',
    'QENTA_CHECKOUT_PAGE_EPAY_BG_LABEL' => 'ePay.bg',
    'QENTA_CHECKOUT_PAGE_EPS_LABEL' => 'eps Online-&Uuml;berweisung',
    'QENTA_CHECKOUT_PAGE_GIROPAY_LABEL' => 'giropay',
    'QENTA_CHECKOUT_PAGE_IDL_LABEL' => 'iDEAL',
    'QENTA_CHECKOUT_PAGE_INSTALLMENT_LABEL' => 'Kauf auf Raten',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2B_LABEL' => 'Kauf auf Rechnung B2B',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2C_LABEL' => 'Kauf auf Rechnung B2C',
    'QENTA_CHECKOUT_PAGE_MAESTRO_LABEL' => 'Maestro SecureCode',
    'QENTA_CHECKOUT_PAGE_MONETA_LABEL' => 'moneta.ru',
    'QENTA_CHECKOUT_PAGE_MASTERPASS_LABEL' => 'masterpass',
    'QENTA_CHECKOUT_PAGE_PAYPAL_LABEL' => 'PayPal',
    'QENTA_CHECKOUT_PAGE_PBX_LABEL' => 'paybox',
    'QENTA_CHECKOUT_PAGE_POLI_LABEL' => 'POLi',
    'QENTA_CHECKOUT_PAGE_PRZELEWY24_LABEL' => 'Przelewy24',
    'QENTA_CHECKOUT_PAGE_PSC_LABEL' => 'paysafecard',
    'QENTA_CHECKOUT_PAGE_SELECT_LABEL' => 'Zahlungsmittelauswahl',
    'QENTA_CHECKOUT_PAGE_SEPA-DD_LABEL' => 'SEPA Lastschrift',
    'QENTA_CHECKOUT_PAGE_SKRILLWALLET_LABEL' => 'Skrill Digital Wallet',
    'QENTA_CHECKOUT_PAGE_SOFORTUEBERWEISUNG_LABEL' => 'Sofort.',
    'QENTA_CHECKOUT_PAGE_TATRAPAY_LABEL' => 'TatraPay',
    'QENTA_CHECKOUT_PAGE_TRUSTLY_LABEL' => 'Trustly',
    'QENTA_CHECKOUT_PAGE_VOUCHER_LABEL' => 'Mein Gutschein',
    'QENTA_CHECKOUT_PAGE_TRUSTPAY_LABEL' => 'TrustPay',
    'QENTA_CHECKOUT_PAGE_BANCONTACT_MISTERCASH_DESC' => '',
    'QENTA_CHECKOUT_PAGE_CCARD_DESC' => '',
    'QENTA_CHECKOUT_PAGE_CCARD-MOTO_DESC' => '',
    'QENTA_CHECKOUT_PAGE_EKONTO_DESC' => '',
    'QENTA_CHECKOUT_PAGE_EPAY_BG_DESC' => '',
    'QENTA_CHECKOUT_PAGE_ELV_DESC' => '',
    'QENTA_CHECKOUT_PAGE_EPS_DESC' => '',
    'QENTA_CHECKOUT_PAGE_GIROPAY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_IDL_DESC' => '',
    'QENTA_CHECKOUT_PAGE_INSTALLMENT_DESC' => '',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2B_DESC' => '',
    'QENTA_CHECKOUT_PAGE_INVOICE_B2C_DESC' => '',
    'QENTA_CHECKOUT_PAGE_MAESTRO_DESC' => '',
    'QENTA_CHECKOUT_PAGE_MONETA_DESC' => '',
    'QENTA_CHECKOUT_PAGE_MASTERPASS_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PAYPAL_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PBX_DESC' => '',
    'QENTA_CHECKOUT_PAGE_POLI_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PRZELEWY24_DESC' => '',
    'QENTA_CHECKOUT_PAGE_PSC_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SELECT_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SEPA-DD_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SKRILLWALLET_DESC' => '',
    'QENTA_CHECKOUT_PAGE_SOFORTUEBERWEISUNG_DESC' => '',
    'QENTA_CHECKOUT_PAGE_TATRAPAY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_TRUSTLY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_VOUCHER_DESC' => '',
    'QENTA_CHECKOUT_PAGE_TRUSTPAY_DESC' => '',
    'QENTA_CHECKOUT_PAGE_COMMUNICATION_ERROR' => 'Kommunikationsfehler zum Zahlungsdienstleister. Bitte versuchen Sie es sp&auml;ter erneut.',
    'QCP_SUBMIT' => 'Senden',
    'QCP_SUBMIT_CONFIG' => 'QENTA Checkout Page Konfiguration senden.',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_RECEIVER' => 'Empf&auml;nger',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_CONFIG_STRING' => 'Konfiguration',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_DESC_TEXT' => 'Kommentar',
    'MODULE_PAYMENT_QCP_EXPORT_CONFIG_RETURN_MAIL' => 'Antwort an E-Mail-Adresse',
    'ORDER_OVERVIEW_QCP_FINANCIALINSTITUTION' => 'financialInstitution',
    'ORDER_OVERVIEW_QCP_LANGUAGE' => 'language',
    'ORDER_OVERVIEW_QCP_ORDERNUMBER' => 'orderNumber',
    'ORDER_OVERVIEW_QCP_AMOUNT' => 'amount',
    'ORDER_OVERVIEW_QCP_CURRENCY' => 'currency',
    'ORDER_OVERVIEW_QCP_GATEWAYCONTRACTNUMBER' => 'gatewayContractNumber',
    'ORDER_OVERVIEW_QCP_GATEWAYREFERENCENUMBER' => 'gatewayReferenceNumber',
    'ORDER_OVERVIEW_QCP_MESSAGE' => 'message',
    'ORDER_OVERVIEW_QCP_LIABILITYSHIFTINDICATOR' => 'liabilityShiftIndicator',
    'ORDER_OVERVIEW_QCP_INSTRUMENTCOUNTRY' => 'instrumentCountry',
    'ORDER_OVERVIEW_QCP_RISKINTERCEPT' => 'riskIntercept',
    'ORDER_OVERVIEW_QCP_RISKREASONCODE' => 'riskReasonCode',
    'ORDER_OVERVIEW_QCP_RISKREASONMESSAGE' => 'riskReasonMessage',
    'ORDER_OVERVIEW_QCP_RISKRETURNCODE' => 'riskReturnCode',
    'ORDER_OVERVIEW_QCP_RISKRETURNMESSAGE' => 'riskReturnMessage',
    'ORDER_OVERVIEW_QCP_PAYMENTSTATE' => 'paymentState',
    'ORDER_OVERVIEW_QCP_LANG' => 'lang',
    'ORDER_OVERVIEW_QCP_LANGID' => 'langId',
    'ORDER_OVERVIEW_QCP_CHECKOUTTYPE' => 'checkoutType',
    'ORDER_OVERVIEW_QCP_AVSRESPONSECODE' => 'avsResponseCode',
    'ORDER_OVERVIEW_QCP_AVSRESPONSEMESSAGE' => 'avsResponseMessage',
    'ORDER_OVERVIEW_QCP_AVSPROVIDERRESULTCODE' => 'avsProviderResultCode',
    'ORDER_OVERVIEW_QCP_AVSPROVIDERRESULTMESSAGE' => 'avsProviderResultMessage',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERNAME' => 'idealConsumerName',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERBIC' => 'idealConsumerBIC',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERCITY' => 'idealConsumerCity',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERIBAN' => 'idealConsumerIBAN',
    'ORDER_OVERVIEW_QCP_IDEALCONSUMERACCOUNTNUMBER' => 'idealConsumerAccountNumber',
    'ORDER_OVERVIEW_QCP_SENDERACCOUNTOWNER' => 'senderAccountOwner',
    'ORDER_OVERVIEW_QCP_SENDERACCOUNTNUMBER' => 'senderAccountNumber',
    'ORDER_OVERVIEW_QCP_SENDERBANKNUMBER' => 'senderBankNumber',
    'ORDER_OVERVIEW_QCP_SENDERBANKNAME' => 'senderBankName',
    'ORDER_OVERVIEW_QCP_SENDERBIC' => 'senderBIC',
    'ORDER_OVERVIEW_QCP_SENDERIBAN' => 'senderIBAN',
    'ORDER_OVERVIEW_QCP_SENDERCOUNTRY' => 'senderCountry',
    'ORDER_OVERVIEW_QCP_SECURITYCRITERIA' => 'securityCriteria',
    'ORDER_OVERVIEW_QCP_AUTHENTICATED' => ' authenticated ',
    'ORDER_OVERVIEW_QCP_ANONYMOUSPAN' => 'anonymousPan',
    'ORDER_OVERVIEW_QCP_EXPIRY' => 'expiry',
    'ORDER_OVERVIEW_QCP_CARDHOLDER' => 'cardholder',
    'ORDER_OVERVIEW_QCP_MASKEDPAN' => 'maskedPan',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERID' => 'paypalPayerID',
    'ORDER_OVERVIEW_QCP_PAYPALPAYEREMAIL' => 'paypalPayerEmail',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERLASTNAME' => 'paypalPayerLastName',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERFIRSTNAME' => 'paypalPayerFirstName',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSNAME' => 'paypalPayerAddressName',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSCOUNTRY' => 'paypalPayerAddressCountry',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSCOUNTRYCODE' => 'paypalPayerAddressCountryCode',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSCITY' => 'paypalPayerAddressCity',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSSTATE' => 'paypalPayerAddressState',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSSTREET1' => 'paypalPayerAddressStreet1',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSSTREET2' => 'paypalPayerAddressStreet2',
    'ORDER_OVERVIEW_QCP_PAYPALPAYERADDRESSZIP' => 'paypalPayerAddressZIP',
    'ORDER_OVERVIEW_QCP_MANDATEID' => 'mandateId',
    'ORDER_OVERVIEW_QCP_MANDATESIGNATUREDATE' => 'mandateSignatureDate',
    'ORDER_OVERVIEW_QCP_CREDITORID' => 'creditorId',
    'ORDER_OVERVIEW_QCP_DUEDATE' => 'dueDate',
);
