<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard Central Eastern Europe GmbH
 * (abbreviated to Wirecard CEE) and are explicitly not part of the Wirecard CEE range of
 * products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 2 (GPLv2) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard CEE does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard CEE does not guarantee their full
 * functionality neither does Wirecard CEE assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard CEE does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */

$sLangName = "English";

$aLang = array(
    "charset" => 'UTF-8',
    'SHOP_MODULE_GROUP_wcp_parameters' => 'Parameter Configurations',
    'SHOP_MODULE_sWcpCustomerId' => 'Customer ID',
    'HELP_SHOP_MODULE_sWcpCustomerId' => 'Customer number you received from Wirecard (customerId, i.e.(D2#####).<br /><a href="https://guides.wirecard.at/request_parameters#customerid" target="_blank">More information: customerId</a>',
    'SHOP_MODULE_sWcpShopId' => 'Shop ID',
    'HELP_SHOP_MODULE_sWcpShopId' => 'Shop identifier (<a href="https://guides.wirecard.at/request_parameters#shopid" target="_blank">shopId</a>) in case of more than one shop. Please contact our <a href="https://guides.wirecard.at/sales" target="_blank">sales teams</a> to activate this feature. <br /><a href="https://guides.wirecard.at/request_parameters#shopid" target="_blank">More information: shopId</a>',
    'SHOP_MODULE_sWcpSecret' => 'Secret',
    'HELP_SHOP_MODULE_sWcpSecret' => 'String which you received from Wirecard for signing and validating data to prove their authenticity. <br /><a href="https://guides.wirecard.at/security:start#secret_and_fingerprint" target="_blank">More information: secret</a>',
    'SHOP_MODULE_sWcpImageUrl' => 'URL to image on payment page',
    'HELP_SHOP_MODULE_sWcpImageUrl' => 'URL to an image/logo which is displayed during the payment process in Wirecard Checkout Page. <a href="https://guides.wirecard.at/request_parameters#imageurl" target="_blank">More information: imageUrl</a>',
    'SHOP_MODULE_sWcpServiceUrl' => 'URL to imprint page',
    'HELP_SHOP_MODULE_sWcpServiceUrl' => 'URL on the payment page which leads to the imprint page of the online shop. <a href="https://guides.wirecard.at/request_parameters#serviceurl" target="_blank">More information: serviceUrl</a>',
    'SHOP_MODULE_sWcpDisplayText' => 'Text on payment page',
    'HELP_SHOP_MODULE_sWcpDisplayText' => 'Text displayed during the payment process, i.e. "Thank you for ordering in xy-shop". <a href="https://guides.wirecard.at/request_parameters#displaytext" target="_blank">More information: displayText</a>',
    'SHOP_MODULE_bWcpAutoDeposit' => 'Automated deposit',
    'HELP_SHOP_MODULE_bWcpAutoDeposit' => 'Enabling an automated deposit of payments.  <a href="https://guides.wirecard.at/request_parameters#autodeposit" target="_blank">More information</a>. Please contact our <a href="https://guides.wirecard.at/sales" target="_blank">sales teams</a> to activate this feature.',
    'SHOP_MODULE_sWcpBackgroundColor' => 'Background color for credit card logos',
    'HELP_SHOP_MODULE_sWcpBackgroundColor' => 'Background color for the image containing the credit card brand logos. <a href="https://guides.wirecard.at/request_parameters#backgroundcolor" target="_blank">More information: backgroundColor</a>',
    'SHOP_MODULE_bWcpUseLayout' => 'Device type optimization',
    'HELP_SHOP_MODULE_bWcpUseLayout' => 'Forward device type for which Wirecard Checkout Page should be optimized ("desktop", "tablet" or "smartphone"; parameter <a href="https://guides.wirecard.at/request_parameters#layout" target="_blank">layout</a>). Please contact our <a href="https://guides.wirecard.at/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.wirecard.at/request_parameters#layout" target="_blank">More information: layout</a>',
    'SHOP_MODULE_sWcpPluginMode' => 'Plugin mode',
    'SHOP_MODULE_sWcpPluginMode_Demo' => 'Demo',
    'SHOP_MODULE_sWcpPluginMode_Test' => 'Test',
    'SHOP_MODULE_sWcpPluginMode_Live' => 'Production',
    'HELP_SHOP_MODULE_sWcpPluginMode' => 'For integration, select predefined configuration settings or "Production" for live systems.',
    'SHOP_MODULE_bWcpDuplicateRequestCheck' => 'Check for duplicate requests',
    'HELP_SHOP_MODULE_bWcpDuplicateRequestCheck' => 'Checking duplicate requests made by your consumer. <a href="https://guides.wirecard.at/request_parameters#duplicaterequestcheck" target="_blank">More information: duplicateRequestCheck</a>',
    'SHOP_MODULE_sWcpConfirmMail' => 'Notification e-mail',
    'HELP_SHOP_MODULE_sWcpConfirmMail' => 'Receiving notification by e-mail regarding the orders of your consumers if an error occurred in the communication between Wirecard and your online shop. Please contact our <a href="https://guides.wirecard.at/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.wirecard.at/request_parameters#confirmmail" target="_blank">More information: confirmMail</a>',
    'SHOP_MODULE_sWcpMaxRetries' => 'Max. retries',
    'HELP_SHOP_MODULE_sWcpMaxRetries' => 'Definition of maximum number of payment attempts regarding a certain order. Please contact our <a href="https://guides.wirecard.at/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.wirecard.at/request_parameters#maxretries" target="_blank">More information: maxRetries</a>',
    'SHOP_MODULE_sWcpPaymentTypeSortOrder' => 'Payment method sort order',
    'HELP_SHOP_MODULE_sWcpPaymentTypeSortOrder' => 'Sort order of payment methods and sub-methods in the payment method selection area. Please contact our <a href="https://guides.wirecard.at/sales" target="_blank">sales teams</a> to activate this feature.<br /><a href="https://guides.wirecard.at/request_parameters#paymenttypesortorder" target="_blank">More information: paymenttypeSortOrder</a>',
    'SHOP_MODULE_GROUP_wcp_settings' => 'Plugin Configuration',
    'SHOP_MODULE_bWcpSendAdditionalCustomerData' => 'Forward consumer data',
    'HELP_SHOP_MODULE_bWcpSendAdditionalCustomerData' => 'Forwarding shipping and billing data about your consumer to the respective financial service provider.',
    'SHOP_MODULE_bWcpSendAdditionalBasketData' => 'Forward basket data',
    'HELP_SHOP_MODULE_bWcpSendAdditionalBasketData' => 'Forwarding basket data to the respective financial service provider.',
    'SHOP_MODULE_bWcpLogConfirmations' => 'Save payment process results',
    'HELP_SHOP_MODULE_bWcpLogConfirmations' => 'Save all results regarding the payment process, i.e. each Wirecard Checkout Server response to the confirmation URL.',
    'SHOP_MODULE_sWcpCheckoutFolder' => 'Folder for initiated orders',
    'HELP_SHOP_MODULE_sWcpCheckoutFolder' => 'Selecting folder into which new orders are stored.',
    'SHOP_MODULE_sWcpCheckoutFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sWcpCheckoutFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sWcpCheckoutFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sWcpSuccessFolder' => 'Folder for orders with successful payment',
    'HELP_SHOP_MODULE_sWcpSuccessFolder' => 'Selecting folder into which successful orders are stored.',
    'SHOP_MODULE_sWcpSuccessFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sWcpSuccessFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sWcpSuccessFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sWcpPendingFolder' => 'Folder for orders with pending payment',
    'HELP_SHOP_MODULE_sWcpPendingFolder' => 'Selecting folder into which pending orders are stored.',
    'SHOP_MODULE_sWcpPendingFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sWcpPendingFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sWcpPendingFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sWcpCancelFolder' => 'Folder for orders with canceled payment',
    'HELP_SHOP_MODULE_sWcpCancelFolder' => 'Selecting folder into which canceled orders are stored.',
    'SHOP_MODULE_sWcpCancelFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sWcpCancelFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sWcpCancelFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_sWcpFailureFolder' => 'Folder for orders with failed payment',
    'HELP_SHOP_MODULE_sWcpFailureFolder' => 'Selecting folder into which failed orders are stored.',
    'SHOP_MODULE_sWcpFailureFolder_ORDERFOLDER_NEW' => 'New',
    'SHOP_MODULE_sWcpFailureFolder_ORDERFOLDER_FINISHED' => 'Finished',
    'SHOP_MODULE_sWcpFailureFolder_ORDERFOLDER_PROBLEMS' => 'Problems',
    'SHOP_MODULE_bWcpDisableDeviceDetection' => 'Disable iframe for mobile devices',
    'HELP_SHOP_MODULE_bWcpDisableDeviceDetection' => 'Redirect your consumer instead of displaying Wirecard Checkout Page in an iframe when visiting your online shop using a mobile device or a tablet.',
    'SHOP_MODULE_sWcpShopName' => 'Shop prefix in posting text',
    'HELP_SHOP_MODULE_sWcpShopName' => 'Reference to your online shop on your consumer\'s invoice, limited to 9 characters (used together with the order number to create the parameter <a href="https://guides.wirecard.at/request_parameters#customerstatement" target="_blank">customerStatement</a>',
    'SHOP_MODULE_GROUP_wcp_iframe_settings' => 'Iframe settings',
    'SHOP_MODULE_bWcp_bancontact_mistercash_UseIframe' => 'Bancontact - use iframe',
    'SHOP_MODULE_bWcp_ccard_UseIframe' => 'Credit Card - use iframe',
    'SHOP_MODULE_bWcp_ccard-moto_UseIframe' => 'Credit Card Mail Order / Telephone Order - use iframe',
    'SHOP_MODULE_bWcp_masterpass_UseIframe' => 'masterpass - use iframe',
    'SHOP_MODULE_bWcp_ekonto_UseIframe' => 'eKonto - use iframe',
    'SHOP_MODULE_bWcp_epay_bg_UseIframe' => 'ePay.bg - use iframe',
    'SHOP_MODULE_bWcp_eps_UseIframe' => 'eps Online-&Uuml;berweisung - use iframe',
    'SHOP_MODULE_bWcp_giropay_UseIframe' => 'giropay - use iframe',
    'SHOP_MODULE_bWcp_idl_UseIframe' => 'iDEAL - use iframe',
    'SHOP_MODULE_bWcp_installment_UseIframe' => 'Installment - use iFrame',
    'SHOP_MODULE_bWcp_invoice_b2b_UseIframe' => 'Invoice B2B - use iframe',
    'SHOP_MODULE_bWcp_invoice_b2c_UseIframe' => 'Invoice B2C - use iframe',
    'SHOP_MODULE_bWcp_maestro_UseIframe' => 'Maestro SecureCode - use iframe',
    'SHOP_MODULE_bWcp_moneta_UseIframe' => 'moneta.ru - use iframe',
    'SHOP_MODULE_bWcp_paypal_UseIframe' => 'PayPal - use iframe',
    'SHOP_MODULE_bWcp_pbx_UseIframe' => 'paybox - use iframe',
    'SHOP_MODULE_bWcp_poli_UseIframe' => 'POLi - use iframe',
    'SHOP_MODULE_bWcp_przelewy24_UseIframe' => 'Przelewy24 - use iframe',
    'SHOP_MODULE_bWcp_psc_UseIframe' => 'paysafecard - use iframe',
    'SHOP_MODULE_bWcp_quick_UseIframe' => '@Quick - use iframe',
    'SHOP_MODULE_bWcp_select_UseIframe' => 'Payment Selection - use iframe',
    'SHOP_MODULE_bWcp_sepa-dd_UseIframe' => 'SEPA Direct Debit - use iframe',
    'SHOP_MODULE_bWcp_skrillwallet_UseIframe' => 'Skrill Digital Wallet - use iframe',
    'SHOP_MODULE_bWcp_sofortueberweisung_UseIframe' => 'Online bank transfer. - use iframe',
    'SHOP_MODULE_bWcp_tatrapay_UseIframe' => 'TatraPay - use iframe',
    'SHOP_MODULE_bWcp_trustly_UseIframe' => 'Trustly - use iframe',
    'SHOP_MODULE_bWcp_voucher_UseIframe' => 'My Voucher - use iframe',
    'SHOP_MODULE_bWcp_trustpay_UseIframe' => 'TrustPay - use iframe',
    'SHOP_MODULE_GROUP_wcp_installment_invoice_settings' => 'Installment/Invoice Settings',
    'SHOP_MODULE_sWcpInstallmentProvider' => 'Installment Provider',
    'SHOP_MODULE_sWcpInvoiceProvider' => 'Invoice Provider',
    'HELP_SHOP_MODULE_sWcpInvoiceProvider' => 'Set respective invoice provider. Input will be ignored if invoice is not enabled.',
    'HELP_SHOP_MODULE_sWcpInstallmentProvider' => 'Set respective installment provider. Input will be ignored if installment is not enabled.',
    'SHOP_MODULE_sWcpInvoiceProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sWcpInvoiceProvider_WIRECARD' => 'Wirecard',
    'SHOP_MODULE_sWcpInvoiceProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_sWcpInstallmentProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sWcpInstallmentProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_bWcpPayolutionAllowDifferingAddresses' => 'For payolution: Allowing shipping address to differ from billing address.',
    'SHOP_MODULE_bWcpInvoiceb2bTrustedShopsCheckbox' => 'Display "Trusted Shops"-checkbox for payolution invoice B2B',
    'HELP_SHOP_MODULE_bWcpInvoiceb2bTrustedShopsCheckbox' => 'If your online shop is certified by "Trusted Shops", display the corresponding checkbox with payolution terms for the consumer to agree with during the checkout process.',
    'SHOP_MODULE_bWcpInvoiceb2cTrustedShopsCheckbox' => 'Display "Trusted Shops"-checkbox for payolution invoice B2C',
    'HELP_SHOP_MODULE_bWcpInvoiceb2cTrustedShopsCheckbox' => 'If your online shop is certified by "Trusted Shops", display the corresponding checkbox with payolution terms for the consumer to agree with during the checkout process.',
    'SHOP_MODULE_bWcpInstallmentTrustedShopsCheckbox' => 'Display "Trusted Shops"-checkbox for payolution installment',
    'HELP_SHOP_MODULE_bWcpInstallmentTrustedShopsCheckbox' => 'If your online shop is certified by "Trusted Shops", display the corresponding checkbox with payolution terms for the consumer to agree with during the checkout process.',
    'SHOP_MODULE_sWcpPayolutionMId' => 'payolution mID',
    'HELP_SHOP_MODULE_sWcpPayolutionMId' => 'Your payolution merchant ID consisting of the base64-encoded company name which is used in the link for "consent" to the payolution terms.(https://www.base64encode.org/)',
    'WIRECARD_CHECKOUT_PAGE_BANCONTACT_MISTERCASH_LABEL' => 'Bancontact',
    'WIRECARD_CHECKOUT_PAGE_CCARD_LABEL' => 'Credit Card',
    'WIRECARD_CHECKOUT_PAGE_CCARD-MOTO_LABEL' => 'Credit Card Mail Order / Telephone Order',
    'WIRECARD_CHECKOUT_PAGE_EKONTO_LABEL' => 'eKonto',
    'WIRECARD_CHECKOUT_PAGE_EPAY_BG_LABEL' => 'ePay.bg',
    'WIRECARD_CHECKOUT_PAGE_EPS_LABEL' => 'eps Online-&Uuml;berweisung',
    'WIRECARD_CHECKOUT_PAGE_GIROPAY_LABEL' => 'giropay',
    'WIRECARD_CHECKOUT_PAGE_IDL_LABEL' => 'iDEAL',
    'WIRECARD_CHECKOUT_PAGE_INSTALLMENT_LABEL' => 'Installment',
    'WIRECARD_CHECKOUT_PAGE_INVOICE_B2B_LABEL' => 'Invoice B2B',
    'WIRECARD_CHECKOUT_PAGE_INVOICE_B2C_LABEL' => 'Invoice B2C',
    'WIRECARD_CHECKOUT_PAGE_MAESTRO_LABEL' => 'Maestro SecureCode',
    'WIRECARD_CHECKOUT_PAGE_MONETA_LABEL' => 'moneta.ru',
    'WIRECARD_CHECKOUT_PAGE_MASTERPASS_LABEL' => 'masterpass',
    'WIRECARD_CHECKOUT_PAGE_PAYPAL_LABEL' => 'PayPal',
    'WIRECARD_CHECKOUT_PAGE_PBX_LABEL' => 'paybox',
    'WIRECARD_CHECKOUT_PAGE_POLI_LABEL' => 'POLi',
    'WIRECARD_CHECKOUT_PAGE_PRZELEWY24_LABEL' => 'Przelewy24',
    'WIRECARD_CHECKOUT_PAGE_PSC_LABEL' => 'paysafecard',
    'WIRECARD_CHECKOUT_PAGE_QUICK_LABEL' => '@Quick',
    'WIRECARD_CHECKOUT_PAGE_SELECT_LABEL' => 'Payment Selection',
    'WIRECARD_CHECKOUT_PAGE_SEPA-DD_LABEL' => 'SEPA Direct Debit',
    'WIRECARD_CHECKOUT_PAGE_SKRILLWALLET_LABEL' => 'Skrill Digital Wallet',
    'WIRECARD_CHECKOUT_PAGE_SOFORTUEBERWEISUNG_LABEL' => 'Online bank transfer.',
    'WIRECARD_CHECKOUT_PAGE_TATRAPAY_LABEL' => 'TatraPay',
    'WIRECARD_CHECKOUT_PAGE_TRUSTLY_LABEL' => 'Trustly',
    'WIRECARD_CHECKOUT_PAGE_VOUCHER_LABEL' => 'My Voucher',
    'WIRECARD_CHECKOUT_PAGE_TRUSTPAY_LABEL' => 'TrustPay',
    'WIRECARD_CHECKOUT_PAGE_BANCONTACT_MISTERCASH_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_CCARD_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_CCARD-MOTO_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_EKONTO_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_EPAY_BG_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_ELV_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_EPS_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_GIROPAY_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_IDL_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_INSTALLMENT_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_INVOICE_B2B_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_INVOICE_B2C_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_MAESTRO_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_MONETA_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_MASTERPASS_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_PAYPAL_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_PBX_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_POLI_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_PRZELEWY24_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_PSC_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_QUICK_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_SELECT_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_SEPA-DD_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_SKRILLWALLET_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_SOFORTUEBERWEISUNG_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_TATRAPAY_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_TRUSTLY_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_VOUCHER_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_TRUSTPAY_DESC' => '',
    'WIRECARD_CHECKOUT_PAGE_COMMUNICATION_ERROR' => 'Communication error with payment service provider. Please try again later.',
    'WCP_SUBMIT' => 'Submit',
    'WCP_SUBMIT_CONFIG' => 'Submit Wirecard Checkout Page Configuration',
    'MODULE_PAYMENT_WCP_EXPORT_CONFIG_RECEIVER' => 'Send to',
    'MODULE_PAYMENT_WCP_EXPORT_CONFIG_CONFIG_STRING' => 'Configuration',
    'MODULE_PAYMENT_WCP_EXPORT_CONFIG_DESC_TEXT' => 'Comment',
    'MODULE_PAYMENT_WCP_EXPORT_CONFIG_RETURN_MAIL' => 'Reply to e-mail address',
    'ORDER_OVERVIEW_WCP_FINANCIALINSTITUTION' => 'financialInstitution',
    'ORDER_OVERVIEW_WCP_LANGUAGE' => 'language',
    'ORDER_OVERVIEW_WCP_ORDERNUMBER' => 'orderNumber',
    'ORDER_OVERVIEW_WCP_AMOUNT' => 'amount',
    'ORDER_OVERVIEW_WCP_CURRENCY' => 'currency',
    'ORDER_OVERVIEW_WCP_GATEWAYCONTRACTNUMBER' => 'gatewayContractNumber',
    'ORDER_OVERVIEW_WCP_GATEWAYREFERENCENUMBER' => 'gatewayReferenceNumber',
    'ORDER_OVERVIEW_WCP_MESSAGE' => 'message',
    'ORDER_OVERVIEW_WCP_LIABILITYSHIFTINDICATOR' => 'liabilityShiftIndicator',
    'ORDER_OVERVIEW_WCP_INSTRUMENTCOUNTRY' => 'instrumentCountry',
    'ORDER_OVERVIEW_WCP_RISKINTERCEPT' => 'riskIntercept',
    'ORDER_OVERVIEW_WCP_RISKREASONCODE' => 'riskReasonCode',
    'ORDER_OVERVIEW_WCP_RISKREASONMESSAGE' => 'riskReasonMessage',
    'ORDER_OVERVIEW_WCP_RISKRETURNCODE' => 'riskReturnCode',
    'ORDER_OVERVIEW_WCP_RISKRETURNMESSAGE' => 'riskReturnMessage',
    'ORDER_OVERVIEW_WCP_PAYMENTSTATE' => 'paymentState',
    'ORDER_OVERVIEW_WCP_LANG' => 'lang',
    'ORDER_OVERVIEW_WCP_LANGID' => 'langId',
    'ORDER_OVERVIEW_WCP_CHECKOUTTYPE' => 'checkoutType',
    'ORDER_OVERVIEW_WCP_AVSRESPONSECODE' => 'avsResponseCode',
    'ORDER_OVERVIEW_WCP_AVSRESPONSEMESSAGE' => 'avsResponseMessage',
    'ORDER_OVERVIEW_WCP_AVSPROVIDERRESULTCODE' => 'avsProviderResultCode',
    'ORDER_OVERVIEW_WCP_AVSPROVIDERRESULTMESSAGE' => 'avsProviderResultMessage',
    'ORDER_OVERVIEW_WCP_IDEALCONSUMERNAME' => 'idealConsumerName',
    'ORDER_OVERVIEW_WCP_IDEALCONSUMERBIC' => 'idealConsumerBIC',
    'ORDER_OVERVIEW_WCP_IDEALCONSUMERCITY' => 'idealConsumerCity',
    'ORDER_OVERVIEW_WCP_IDEALCONSUMERIBAN' => 'idealConsumerIBAN',
    'ORDER_OVERVIEW_WCP_IDEALCONSUMERACCOUNTNUMBER' => 'idealConsumerAccountNumber',
    'ORDER_OVERVIEW_WCP_SENDERACCOUNTOWNER' => 'senderAccountOwner',
    'ORDER_OVERVIEW_WCP_SENDERACCOUNTNUMBER' => 'senderAccountNumber',
    'ORDER_OVERVIEW_WCP_SENDERBANKNUMBER' => 'senderBankNumber',
    'ORDER_OVERVIEW_WCP_SENDERBANKNAME' => 'senderBankName',
    'ORDER_OVERVIEW_WCP_SENDERBIC' => 'senderBIC',
    'ORDER_OVERVIEW_WCP_SENDERIBAN' => 'senderIBAN',
    'ORDER_OVERVIEW_WCP_SENDERCOUNTRY' => 'senderCountry',
    'ORDER_OVERVIEW_WCP_SECURITYCRITERIA' => 'securityCriteria',
    'ORDER_OVERVIEW_WCP_AUTHENTICATED' => ' authenticated ',
    'ORDER_OVERVIEW_WCP_ANONYMOUSPAN' => 'anonymousPan',
    'ORDER_OVERVIEW_WCP_EXPIRY' => 'expiry',
    'ORDER_OVERVIEW_WCP_CARDHOLDER' => 'cardholder',
    'ORDER_OVERVIEW_WCP_MASKEDPAN' => 'maskedPan',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERID' => 'paypalPayerID',
    'ORDER_OVERVIEW_WCP_PAYPALPAYEREMAIL' => 'paypalPayerEmail',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERLASTNAME' => 'paypalPayerLastName',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERFIRSTNAME' => 'paypalPayerFirstName',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSNAME' => 'paypalPayerAddressName',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSCOUNTRY' => 'paypalPayerAddressCountry',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSCOUNTRYCODE' => 'paypalPayerAddressCountryCode',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSCITY' => 'paypalPayerAddressCity',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSSTATE' => 'paypalPayerAddressState',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSSTREET1' => 'paypalPayerAddressStreet1',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSSTREET2' => 'paypalPayerAddressStreet2',
    'ORDER_OVERVIEW_WCP_PAYPALPAYERADDRESSZIP' => 'paypalPayerAddressZIP',
    'ORDER_OVERVIEW_WCP_MANDATEID' => 'mandateId',
    'ORDER_OVERVIEW_WCP_MANDATESIGNATUREDATE' => 'mandateSignatureDate',
    'ORDER_OVERVIEW_WCP_CREDITORID' => 'creditorId',
    'ORDER_OVERVIEW_WCP_DUEDATE' => 'dueDate',
);
